name: "CI Pipeline Backend"

on:
  push:
  pull_request:
    branches:
      - master
  schedule: # run once a month
    - cron: '0 0 1 * *'

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup python venv
        run: source ./backend/venv/bin/activate
      - name: Run PyLint
        working-directory: ./backend
        run: pylint app
